config/routes.rb
Rails.application.routes.draw do
  root 'admin#index'

  resources :orders, only: [:index, :show], param: :number

  resources :reports, only: :index
  get 'reports/coupons', to: 'reports#coupons'
  get 'reports/sales', to: 'reports#sales'
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of   :address1, :city, :state, :user_id
  validates_uniqueness_of :user_id

  validates :zipcode,
            format: {
              with: /\A\d{5}\z/,
              message: "not valid. Please enter your 5 digit zipcode"
            }, presence: true

  belongs_to :user

  has_many   :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  validates_presence_of :name

  validates   :amount,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  has_many :order_items,
           as: :source
end

app/models/order.rb
class Order < ApplicationRecord
  BUILDING = "building"
  ARRIVED = "arrived"
  CANCELED = "canceled"
  STATES = [BUILDING, ARRIVED, CANCELED].freeze

  validates_presence_of :user_id, :state

  validates   :total,
              presence: true,
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  belongs_to :user
  belongs_to :address

  has_many :order_items
  has_many :payments

  def to_param
    number
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  SOLD = "sold"
  RETURNED = "returned"
  STATES = [SOLD, RETURNED].freeze
  validates_presence_of :order_id, :source_id, :source_type, :price

  validates :state,
            absence: true,
            if: -> { source_type != Product.name }

  validates :state,
            allow_nil: false,
            inclusion: STATES,
            if: -> { source_type == Product.name && order.building_at.present? }

  validates :quantity,
            presence: true,
            numericality: {
              greater_than: 0
            }

  belongs_to :order
  belongs_to :source,
             polymorphic: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  COMPLETED = "completed"
  REFUNDED = "refunded"
  STATES = [COMPLETED, REFUNDED].freeze

  CREDIT_CARD = "CreditCard"
  STORE_CREDIT = "StoreCredit"
  PAYMENT_TYPES = [CREDIT_CARD, STORE_CREDIT].freeze

  validates_presence_of :order_id, :state, :payment_type

  validates   :amount,
              presence: true,
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name

  validates   :sku,
              presence: true,
              uniqueness: true

  validates   :msrp,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  validates   :cost,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  has_many :order_items,
           as: :source
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :name,
            presence: true

  validates :rate,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 1
            },
            format: {
              with: /\A-?\d+\.?\d{0,3}\z/,
              message: 'only accepts 3 decimal places.'
            }

  has_many :order_items,
           as: :source
end

app/models/user.rb
class User < ApplicationRecord

  validates :name,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true

  has_many :orders
  has_many :addresses
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    orders
  end

  def show
    if order.nil?
      flash.alert = 'Invalid order number'
      return redirect_to orders_url
    end
    product_items
  end

  private
  def order
    @order ||= Order.includes(:user, :payments, order_items: [:source]).find_by(number: permitted_params[:number])
  end

  def orders
    @orders ||= Order.includes(:user).all
  end

  def product_items
    @product_items ||= order.order_items.select {|item| item.source_type == "Product" }
  end

  PERMITTED_PARAMS = %i[number]
  def permitted_params
    params.permit(PERMITTED_PARAMS)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
  end

  def coupons
    all_coupons
    if coupon_name
      valid_coupon? ? set_coupon_data : flash.alert = "Please enter a valid coupon name."
    end
  end

  def sales
    if dates_present?
      valid_dates? ? set_sales_data : flash.alert = "Please enter valid dates."
    end
  end

  private
  def all_coupons
    @all_coupons ||= Coupon.all
  end

  def coupon_name
    @coupon_name ||= permitted_params[:coupon_name]
  end

  def dates_present?
    permitted_params[:start] || permitted_params[:end]
  end

  def valid_dates?
    return false if start_date.nil? || end_date.nil?
    start_date < end_date
  end

  def valid_coupon?
    all_coupons.map(&:name).include? coupon_name
  end

  def start_date
    @start_date ||= DateTime.parse permitted_params[:start] rescue nil
  end

  def end_date
    @end_date ||= DateTime.parse permitted_params[:end] rescue nil
  end

  # if i had more time, i would consider extracting these queries into service objects, which would
  # allow for better rspec testing. but given the time constraints of this project and the complexity
  # of setting up data for testing database interactions, i decided to keep this simple
  def set_coupon_data
    coupon_id = all_coupons.find_by(name: coupon_name)&.id
    return unless coupon_id
    coupon_order_ids = OrderItem.select(:order_id).where(source_type: 'Coupon', source_id: coupon_id)
    coupon_orders =  Order.select('user_id, building_at').where('orders.id in (?)', coupon_order_ids)
    @orders = coupon_orders.map do |order|
      Order.left_joins(:user).select('user_id, count(*) as count, sum(total) as revenue, users.email as user_email').
        where(user_id: order['user_id']).where('building_at > ?', order['building_at'])
    end.flatten
  end

  def set_sales_data
    return if start_date > end_date
    orders = Order.select('id').where('building_at between ? and ?', start_date, end_date).where.not(state: 'canceled')
    order_ids = orders.pluck(:id).join(', ')
    query = %{
      SELECT source_id, sum(quantity) AS total_sold, sum(price * quantity) AS revenue, products.name AS source_name
      FROM order_items
      LEFT JOIN products ON order_items.source_id = products.id
      WHERE order_id IN (#{order_ids}) AND state = 'sold' AND source_type = 'Product'
      GROUP BY source_id
      ORDER BY source_name
    }
    @order_items = ActiveRecord::Base.connection.execute(query)
  end

  QUERY_PARAMS = %i[coupon_name start end]
  def permitted_params
    params.permit(QUERY_PARAMS)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title CodeChallenge

    = csrf_meta_tags
    = csp_meta_tag
    = tag "meta", "http-equiv" => "Accept-CH", content: "DPR, Viewport-Width, Width"
    = tag 'meta', {"http-equiv" => "Accept-CH", content: "width=device-width, initial-scale=1.0, user-scalable=no", name: "viewport", id: "vp"}, true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          =link_to root_path, class: "navbar-brand" do
            =image_tag "logo"

        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{class: current_page?(controller: "orders") ? 'active' : ''}
              =link_to orders_path do
                Orders

            %li{class: current_page?(controller: "reports") ? 'active' : ''}
              =link_to reports_path do
                Reports

    .container-fluid{role: "main"}
      = yield

app/views/orders/index.haml
%h1 Orders
%table{ class: "table" }
  %tr
    %th Name
    %th State
    %th User email
  - if flash.any?
    - flash.each do |_, msg|
      %div{class: 'alert alert-danger'}
        = msg
  - @orders.each do |order|
    .slide
      %tr
        %td= order.number
        %td= order.state
        %td= order.user&.email
        %td
          %a{ href: "/orders/#{order.number}" } View
      %tr
%table

app/views/orders/show.haml
%h1 Order
%table{ class: "table" }
  %tr
    %th Number
    %td= @order.number
  %tr
    %th User name
    %td= @order.user&.name
  %tr
    %th User email
    %td= @order.user&.email
  %tr
    %th Items
    %td
      %table{ class: "table" }
        %th Product name
        %th SKU
        %th MSRP
        %th Cost
        %th Quantity ordered
        %th Price
        %th State
        - @product_items.each do |item|
          .slide
            %tr
              %td= item.source&.name
              %td= item.source&.sku
              %td= number_to_currency(item.source&.msrp)
              %td= number_to_currency(item.source&.cost)
              %td= item.quantity
              %td= item.price
              %td= item.state
  %tr
    %th Payments
    %td
      %table{ class: "table" }
        %th Amount
        %th State
        %th Type
        %th Completed at
        %th Refunded at
        - @order.payments.each do |payment|
          .slide
            %tr
              %td= number_to_currency(payment.amount)
              %td= payment.state
              %td= payment.payment_type
              %td= payment.completed_at
              %td= payment.refunded_at

app/views/reports/coupons.haml
%h2 Select coupon
%h3 View order data for customers after using the selected coupon
%select{ id: 'couponType', onChange: "selectReportType()" }
  %option{ selected: !@coupon_name, disabled: true, hidden: true } Select Coupon
  - @all_coupons.each do |coupon|
    .slide
      %option{ value: coupon.id, selected: @coupon_name == coupon.name }
        = coupon.name
- if flash.any?
  - flash.each do |_, msg|
    %div{class: 'alert alert-danger'}
      = msg
- if @orders
  %table{class: 'table'}
    %tr
      %th User email
      %th Number of orders
      %th Revenue
    - @orders.each do |order|
      .slide
        %tr
          %td= order['user_email']
          %td= order['count']
          %td= number_to_currency(order['revenue'])

app/views/reports/index.haml
= link_to "Coupons", reports_coupons_path
%br
= link_to "Sales", reports_sales_path

app/views/reports/sales.haml
%h2 Select dates
%h3 View all products sold in date range
%form
  %label Start date
  %input{type: "date", id: "salesStartDate"}
  %label End date
  %input{type: "date", id: "salesEndDate"}
  %input{type: "submit", value: "Submit", onClick: "processDates(event)"}
%br
- if flash.any?
  - flash.each do |_, msg|
    %div{class: 'alert alert-danger'}
      = msg
- if @start_date && @end_date
  %h3= "Orders from #{@start_date.strftime('%_m/%-d/%Y')} and #{@end_date.strftime('%_m/%-d/%Y')}"
- if @order_items
  %table{class: 'table'}
    %tr
      %th Product name
      %th Number sold
      %th Total revenue
    - @order_items.each do |item|
      .slide
        %tr
          %th= item['source_name']
          %th= item['total_sold']
          %th= number_to_currency(item['revenue'])